### ISSUE TITLE
Bloblang message functions aren't implemented for `benthos blobl`

### ISSUE THREAD

**Issue by klintan** [Jeffail/benthos#450]
I'm probably misusing bloblang, but there might be a hidden bug somewhere since it segfaults instead of some reasonable (or unreasonable :)) error message.

Running: 

`cat 2-1591144953728675700.jsonl | benthos blobl 'json("from")'`

Results in this:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x16f2016]

goroutine 12 [running]:
github.com/Jeffail/benthos/v3/lib/bloblang/x/query.jsonFunction.func1(0xc0002e4000, 0xc00030a030, 0xc00030a060, 0x0, 0x0, 0x0, 0x0, 0x10, 0x256f940, 0x203001, ...)
	/private/tmp/benthos-20200524-81412-1uczqfg/benthos-3.15.0/src/github.com/Jeffail/benthos/lib/bloblang/x/query/functions.go:158 +0x36
github.com/Jeffail/benthos/v3/lib/bloblang/x/query.closureFn.Exec(0xc000253b00, 0xc0002e4000, 0xc00030a030, 0xc00030a060, 0x0, 0x0, 0x0, 0x0, 0x100e866, 0xc00030a060, ...)
	/private/tmp/benthos-20200524-81412-1uczqfg/benthos-3.15.0/src/github.com/Jeffail/benthos/lib/bloblang/x/query/function_ctor.go:16 +0x58
github.com/Jeffail/benthos/v3/lib/bloblang/x/mapping.(*Executor).Exec(0xc00027a980, 0xc0002e4000, 0xc00030a030, 0xc00030a060, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/private/tmp/benthos-20200524-81412-1uczqfg/benthos-3.15.0/src/github.com/Jeffail/benthos/lib/bloblang/x/mapping/parser.go:110 +0x140
github.com/Jeffail/benthos/v3/lib/service/blobl.run.func3(0xc000351f10, 0xc0004245a0, 0x0, 0xc0006ab250, 0xc00027a980, 0x3e4bc00, 0xc000424600)
	/private/tmp/benthos-20200524-81412-1uczqfg/benthos-3.15.0/src/github.com/Jeffail/benthos/lib/service/blobl/cli.go:108 +0x1da
created by github.com/Jeffail/benthos/v3/lib/service/blobl.run
	/private/tmp/benthos-20200524-81412-1uczqfg/benthos-3.15.0/src/github.com/Jeffail/benthos/lib/service/blobl/cli.go:91 +0x437
```

Running Benthos 
Version: 3.15.0
Date: 2020-05-24T21:52:03Z

Macos 10.14.6

Not sure if it's a specific line that causes this issue but here is an excerpt from the file (81kb):

```
{"kgId": "urn:kg:dbpedia:industrykeyword:entertainment", "kgLabel": "IndustryKeyword", "industryKeywordName.name": "Entertainment", "industryKeywordName.name.original": "Entertainment", "industryKeywordName.name.normalized": "entertainment"}
{"kgId": "urn:kg:dbpedia:organization:achieving-for-children", "kgLabel": "Organization", "description.string_value": "Achieving for Children (AfC) is a social enterprise company created in 2014 by the Royal Borough of Kingston upon Thames and the London Borough of Richmond upon Thames to provide their children\u2019s services. It is thought to have been the first company of its kind. Ofsted rates Achieving for Children as 'outstanding' for children's services in Kingston, following an inspection in October 2019. When the company was launched in 2014, it was described as the 'future model of Children's Services'. It enabled the two councils to save money by sharing services, whilst avoiding some of the \"organisational difficulties\", and allowing them to work in ways that would not be possible as a Local Authority. Some critics were concerned that AfC represented a privatisation of Children' Services, as well as a reduction in accountability and scrutiny, and there was scepticism over whether service levels could be maintained and improved in the wake of significant spending cuts. The organisation was subsequently credited with improving Kingston's Children's Services from an 'Inadequate' to 'Good' Ofsted rating. A 2016 independent Government review of the establishment of AfC concluded that the transformation had demonstrated positive results for service quality and financial return, with a number of benefits realised as well as lessons learned. On 1 August 2017, the Royal Borough of Windsor and Maidenhead became a co-owner of AfC, which now delivers children\u2019s services across all three boroughs. In December 2019, Kingston and Richmond Councils both agreed to recommission Achieving for Children to deliver their children\u2019s services until 31 March 2026.", "description.string_value.original": "Achieving for Children (AfC) is a social enterprise company created in 2014 by the Royal Borough of Kingston upon Thames and the London Borough of Richmond upon Thames to provide their children\u2019s services. It is thought to have been the first company of its kind. Ofsted rates Achieving for Children as 'outstanding' for children's services in Kingston, following an inspection in October 2019. When the company was launched in 2014, it was described as the 'future model of Children's Services'. It enabled the two councils to save money by sharing services, whilst avoiding some of the \"organisational difficulties\", and allowing them to work in ways that would not be possible as a Local Authority. Some critics were concerned that AfC represented a privatisation of Children' Services, as well as a reduction in accountability and scrutiny, and there was scepticism over whether service levels could be maintained and improved in the wake of significant spending cuts. The organisation was subsequently credited with improving Kingston's Children's Services from an 'Inadequate' to 'Good' Ofsted rating. A 2016 independent Government review of the establishment of AfC concluded that the transformation had demonstrated positive results for service quality and financial return, with a number of benefits realised as well as lessons learned. On 1 August 2017, the Royal Borough of Windsor and Maidenhead became a co-owner of AfC, which now delivers children\u2019s services across all three boroughs. In December 2019, Kingston and Richmond Councils both agreed to recommission Achieving for Children to deliver their children\u2019s services until 31 March 2026.", "description.string_value.normalized": "Achieving for Children (AfC) is a social enterprise company created in 2014 by the Royal Borough of Kingston upon Thames and the London Borough of Richmond upon Thames to provide their children\u2019s services. It is thought to have been the first company of its kind. Ofsted rates Achieving for Children as 'outstanding' for children's services in Kingston, following an inspection in October 2019. When the company was launched in 2014, it was described as the 'future model of Children's Services'. It enabled the two councils to save money by sharing services, whilst avoiding some of the \"organisational difficulties\", and allowing them to work in ways that would not be possible as a Local Authority. Some critics were concerned that AfC represented a privatisation of Children' Services, as well as a reduction in accountability and scrutiny, and there was scepticism over whether service levels could be maintained and improved in the wake of significant spending cuts. The organisation was subsequently credited with improving Kingston's Children's Services from an 'Inadequate' to 'Good' Ofsted rating. A 2016 independent Government review of the establishment of AfC concluded that the transformation had demonstrated positive results for service quality and financial return, with a number of benefits realised as well as lessons learned. On 1 August 2017, the Royal Borough of Windsor and Maidenhead became a co-owner of AfC, which now delivers children\u2019s services across all three boroughs. In December 2019, Kingston and Richmond Councils both agreed to recommission Achieving for Children to deliver their children\u2019s services until 31 March 2026.", "organizationName.organization_name.original": "Achieving for Children", "organizationName.organization_name": "Achieving for Children", "organizationName.organization_name.normalized": "achieving-for-children", "dbpediaLink.string_value": "http://dbpedia.org/resource/Achieving_for_Children", "dbpediaLink.string_value.original": "http://dbpedia.org/resource/Achieving_for_Children", "dbpediaLink.string_value.normalized": "http://dbpedia.org/resource/Achieving_for_Children", "homepageURL.url": "https://www.achievingforchildren.org.uk", "homepageURL.url.original": "https://www.achievingforchildren.org.uk", "homepageURL.url.normalized": "achievingforchildren.org.uk", "homepageURL.domain": "achievingforchildren", "homepageURL.domain.original": "achievingforchildren", "homepageURL.domain.normalized": "achievingforchildren"}
{"kgId": "urn:kg:dbpedia:organization:achieving-for-children__urn:kg:dbpedia:source:0__hasSource", "from": "urn:kg:dbpedia:organization:achieving-for-children", "to": "urn:kg:dbpedia:source:0", "kgLabel": "hasSource"}
{"kgId": "urn:kg:dbpedia:organization:achmea", "kgLabel": "Organization", "description.string_value": "Achmea Holding N.V. is one of the largest suppliers of financial services (mainly insurance) in the Netherlands. The company was formed by a merger of Zilveren Kruis and  on January 1, 1995. The roots of Achmea date back to 1811 when the Frisian accountant, , founded the \"Onderlinge Brand Assurantie Soci\u00ebteit (Achlum)\" in Achlum, Frisia, the Netherlands. In 2000 Achmea became a part of Eureko BV, which in 2011 merged with the Dutch parent company Achmea N.V. to form Achmea B.V. The  (association) owns or controls 63.3% of Achmea B.V. of its votes, the Dutch bank Rabobank owns or controls 31.3% of the shares, the other 5.4% of the shares are owned or controlled by strategic partners. Achmea brands include Agis, Av\u00e9ro, Centraal Beheer, FBTO, Interpolis, Syntrus and Zilveren Kruis (often suffixed by 'Achmea'). Of the ten largest insurance companies in the Netherlands, Achmea is one of the two that was found in a 2015 investigation to not invest in arms trade to dictatorships, fragile states and corrupt countries (ASR being the other one).", "description.string_value.original": "Achmea Holding N.V. is one of the largest suppliers of financial services (mainly insurance) in the Netherlands. The company was formed by a merger of Zilveren Kruis and  on January 1, 1995. The roots of Achmea date back to 1811 when the Frisian accountant, , founded the \"Onderlinge Brand Assurantie Soci\u00ebteit (Achlum)\" in Achlum, Frisia, the Netherlands. In 2000 Achmea became a part of Eureko BV, which in 2011 merged with the Dutch parent company Achmea N.V. to form Achmea B.V. The  (association) owns or controls 63.3% of Achmea B.V. of its votes, the Dutch bank Rabobank owns or controls 31.3% of the shares, the other 5.4% of the shares are owned or controlled by strategic partners. Achmea brands include Agis, Av\u00e9ro, Centraal Beheer, FBTO, Interpolis, Syntrus and Zilveren Kruis (often suffixed by 'Achmea'). Of the ten largest insurance companies in the Netherlands, Achmea is one of the two that was found in a 2015 investigation to not invest in arms trade to dictatorships, fragile states and corrupt countries (ASR being the other one).", "description.string_value.normalized": "Achmea Holding N.V. is one of the largest suppliers of financial services (mainly insurance) in the Netherlands. The company was formed by a merger of Zilveren Kruis and  on January 1, 1995. The roots of Achmea date back to 1811 when the Frisian accountant, , founded the \"Onderlinge Brand Assurantie Soci\u00ebteit (Achlum)\" in Achlum, Frisia, the Netherlands. In 2000 Achmea became a part of Eureko BV, which in 2011 merged with the Dutch parent company Achmea N.V. to form Achmea B.V. The  (association) owns or controls 63.3% of Achmea B.V. of its votes, the Dutch bank Rabobank owns or controls 31.3% of the shares, the other 5.4% of the shares are owned or controlled by strategic partners. Achmea brands include Agis, Av\u00e9ro, Centraal Beheer, FBTO, Interpolis, Syntrus and Zilveren Kruis (often suffixed by 'Achmea'). Of the ten largest insurance companies in the Netherlands, Achmea is one of the two that was found in a 2015 investigation to not invest in arms trade to dictatorships, fragile states and corrupt countries (ASR being the other one).", "organizationNameAlias.organization_name.original": "Achmea Holding N.V.", "organizationNameAlias.organization_name": "Achmea Holding N.V.", "organizationNameAlias.organization_name.normalized": "achmea-holding", "organizationName.organization_name.original": "Achmea", "organizationName.organization_name": "Achmea", "organizationName.organization_name.normalized": "achmea", "dbpediaLink.string_value": "http://dbpedia.org/resource/Achmea", "dbpediaLink.string_value.original": "http://dbpedia.org/resource/Achmea", "dbpediaLink.string_value.normalized": "http://dbpedia.org/resource/Achmea", "homepageURL.url": "http://www.achmea.nl", "homepageURL.url.original": "http://www.achmea.nl", "homepageURL.url.normalized": "achmea.nl", "homepageURL.domain": "achmea", "homepageURL.domain.original": "achmea", "homepageURL.domain.normalized": "achmea"}
{"kgId": "urn:kg:dbpedia:organization:achmea__urn:kg:dbpedia:source:0__hasSource", "from": "urn:kg:dbpedia:organization:achmea", "to": "urn:kg:dbpedia:source:0", "kgLabel": "hasSource"}
{"kgId": "urn:kg:dbpedia:organization:achmea__urn:kg:dbpedia:industrykeyword:financial-services__hasIndustryKeyword", "from": "urn:kg:dbpedia:organization:achmea", "to": "urn:kg:dbpedia:industrykeyword:financial-services", "kgLabel": "hasIndustryKeyword"}
```

It's pretty much just dbpedia output and some normalization over the rdf output.

**Comment by Jeffail** [comment]
Hey @klintan, definitely a bug that the crash is happening. When running `benthos blobl` it doesn't have the same concept of a message as when it's used within a pipeline config, and so the function `json("foo")` isn't implemented (as well as `meta`, `from`, etc).

In your case the JSON documents of these lines will already be parsed and so you can just do `benthos blobl 'root = from'`. In Benthos v3.16.0 you can simplify it further into `benthos blobl 'from'` (the `root = ` part is inferred if the mapping is just a query).

I'll fix the crash and make sure `json("foo")` works the same as `this.foo` in the next release.

**Comment by klintan** [comment]
Thanks for your prompt reply. Ah I see. 

Oh nice, I ended up using `this.exists("from")`, but `root = from` might make more sense.

**Comment by Jeffail** [comment]
Fixed in https://github.com/Jeffail/benthos/commit/22f84fc691cf18062cc3d271912f0c8284a4040b
