### ISSUE TITLE
panic when workflow has conditional branch

### ISSUE THREAD

**Issue by ollystephens** [Jeffail/benthos#587]
Running v3.35.0, I encountered a SIGSEGV when authoring a workflow process with conditional branches.
Managed to boil it down to the follow example:

```
pipeline:
  processors:
  - workflow:
      branches:
        A:
          request_map: |
            root = if this.bam == "skip" { deleted() }
          processors:
          - http:
              url: http://localhost:8080/bam
          result_map: |
            root.bam = this
```

The same branch definition outside a workflow does not SEGV.

Stack trace below:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x146f53c]

goroutine 1 [running]:
github.com/Jeffail/benthos/v3/internal/bloblang/query.aggregateTargetPaths.func1(0xc00047e480, 0x0, 0x2ddc06e, 0x5)
	/private/tmp/benthos-20201207-1786-1n95jpz/benthos-3.35.0/internal/bloblang/query/target.go:35 +0x9c
github.com/Jeffail/benthos/v3/internal/bloblang/query.closureFunction.QueryTargets(...)
	/private/tmp/benthos-20201207-1786-1n95jpz/benthos-3.35.0/internal/bloblang/query/function_ctor.go:37
github.com/Jeffail/benthos/v3/internal/bloblang/mapping.(*Executor).QueryTargets(0xc000795b00, 0xc00047e480, 0x10000, 0x41a3158, 0x0)
	/private/tmp/benthos-20201207-1786-1n95jpz/benthos-3.35.0/internal/bloblang/mapping/executor.go:262 +0x137
github.com/Jeffail/benthos/v3/lib/processor.(*Branch).targetsUsed(0xc0002ecd20, 0x0, 0x0, 0x0)
	/private/tmp/benthos-20201207-1786-1n95jpz/benthos-3.35.0/lib/processor/branch.go:285 +0x5b
github.com/Jeffail/benthos/v3/lib/processor.resolveBranchDAG(0xc00089f680, 0xc00089f5f0, 0x40f6be8, 0x1, 0xc000624988, 0xc000866980)
	/private/tmp/benthos-20201207-1786-1n95jpz/benthos-3.35.0/lib/processor/workflow.go:548 +0x191
github.com/Jeffail/benthos/v3/lib/processor.NewWorkflow(0xc0008668f8, 0x8, 0x2ddcefc, 0x6, 0x2e4196f, 0x30, 0x41a3158, 0x0, 0x0, 0x2ddff8f, ...)
	/private/tmp/benthos-20201207-1786-1n95jpz/benthos-3.35.0/lib/processor/workflow.go:487 +0x1625
github.com/Jeffail/benthos/v3/lib/processor.New(0xc0008668f8, 0x8, 0x2ddcefc, 0x6, 0x2e4196f, 0x30, 0x41a3158, 0x0, 0x0, 0x2ddff8f, ...)
	/private/tmp/benthos-20201207-1786-1n95jpz/benthos-3.35.0/lib/processor/constructor.go:507 +0x379
github.com/Jeffail/benthos/v3/lib/pipeline.New.func1(0xc00067ebe0, 0xc00067ebe0, 0x2cc3c40, 0x4, 0x2dda538)
	/private/tmp/benthos-20201207-1786-1n95jpz/benthos-3.35.0/lib/pipeline/constructor.go:74 +0x377
github.com/Jeffail/benthos/v3/lib/pipeline.New(0x1, 0xc000883980, 0x1, 0x1, 0x32ff5a0, 0xc000277ce0, 0x330ac80, 0xc0000912c0, 0x33014c0, 0xc0005982e0, ...)
	/private/tmp/benthos-20201207-1786-1n95jpz/benthos-3.35.0/lib/pipeline/constructor.go:90 +0x159
github.com/Jeffail/benthos/v3/lib/stream.(*Type).start(0xc0008c8000, 0x40f69e0, 0x1010478)
	/private/tmp/benthos-20201207-1786-1n95jpz/benthos-3.35.0/lib/stream/type.go:153 +0x957
github.com/Jeffail/benthos/v3/lib/stream.New(0x2ddc16d, 0x5, 0x2e1d4d9, 0x22, 0x2dea014, 0xd, 0x100, 0x41a3158, 0x0, 0x0, ...)
	/private/tmp/benthos-20201207-1786-1n95jpz/benthos-3.35.0/lib/stream/type.go:50 +0x165
github.com/Jeffail/benthos/v3/lib/service.cmdService(0x7ffeefbff873, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc000110001, 0x0, 0x0, ...)
	/private/tmp/benthos-20201207-1786-1n95jpz/benthos-3.35.0/lib/service/service.go:286 +0x1afb
github.com/Jeffail/benthos/v3/lib/service.Run.func1(0xc0002e7e80, 0xc00011f900, 0xa)
	/private/tmp/benthos-20201207-1786-1n95jpz/benthos-3.35.0/lib/service/run.go:208 +0x225
github.com/urfave/cli/v2.(*App).RunContext(0xc0005a16c0, 0x32e73a0, 0xc00012c160, 0xc000110180, 0x3, 0x3, 0x0, 0x0)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:322 +0x70d
github.com/urfave/cli/v2.(*App).Run(...)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
github.com/Jeffail/benthos/v3/lib/service.Run()
	/private/tmp/benthos-20201207-1786-1n95jpz/benthos-3.35.0/lib/service/run.go:366 +0xc2f
main.main()
	/private/tmp/benthos-20201207-1786-1n95jpz/benthos-3.35.0/cmd/benthos/main.go:8 +0x25
```

**Comment by Jeffail** [comment]
Thanks for the great write up @ollystephens, made it quick to find: https://github.com/Jeffail/benthos/commit/fef1fae99148b30d97fcce9481a14b7e43685ebf

This was an issue with obtaining mapping targets from an if statement without an `else` block, so if you want a temporary work around until this is released you should be able to do `root = if this.bam == "skip" { deleted() } else { this }`.

**Comment by Jeffail** [comment]
Fixed in https://github.com/Jeffail/benthos/releases/tag/v3.36.0
