### ISSUE TITLE
Problems with resource files and rate_limit_resources

### ISSUE THREAD

**Issue by mmsjomu** [Jeffail/benthos#849]
Hi,

first of all thanks for this awesome feature rich product :).

While trying it out and using resource files to structure the project to my liking I stumbled across the following error:

```shell
mmsjomu@orge-dev:~/develop/benthos$ benthos -r "resources/*.yaml"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xe23534]

goroutine 7 [running]:
github.com/Jeffail/benthos/v3/internal/http.(*Client).waitForAccess.func1(0x0, 0x0)
        /home/runner/work/benthos/benthos/internal/http/client.go:260 +0x34
github.com/Jeffail/benthos/v3/lib/manager.(*Type).AccessRateLimit(0xc000dcf360, 0x306cce0, 0xc000fa40c0, 0xc001191a88, 0x12, 0xc000b4c000, 0x0, 0x0)
        /home/runner/work/benthos/benthos/lib/manager/type.go:689 +0xc6
github.com/Jeffail/benthos/v3/internal/interop.AccessRateLimit(0x306cce0, 0xc000fa40c0, 0x3087440, 0xc000dcf360, 0xc001191a88, 0x12, 0xc000b4c000, 0x46f65b, 0x45baac30032)
        /home/runner/work/benthos/benthos/internal/interop/resources.go:178 +0x158
github.com/Jeffail/benthos/v3/internal/http.(*Client).waitForAccess(0xc000e89500, 0x306cce0, 0xc000fa40c0, 0x3087498)
        /home/runner/work/benthos/benthos/internal/http/client.go:259 +0x10d
github.com/Jeffail/benthos/v3/internal/http.(*Client).SendToResponse(0xc000e89500, 0x306cce0, 0xc000fa40c0, 0x3087498, 0xc000f78f60, 0x3087498, 0xc000f79530, 0x0, 0x0, 0x0)
        /home/runner/work/benthos/benthos/internal/http/client.go:496 +0x21c
github.com/Jeffail/benthos/v3/internal/http.(*Client).Send(0xc000e89500, 0x306cce0, 0xc000fa40c0, 0x3087498, 0xc000f78f60, 0x3087498, 0xc000f79530, 0x7f79b8e825b8, 0x10, 0xc0014fc0b0, ...)
        /home/runner/work/benthos/benthos/internal/http/client.go:577 +0x74
github.com/Jeffail/benthos/v3/lib/input.(*HTTPClient).readNotStreamed(0xc000e958c0, 0x306cce0, 0xc000fa40c0, 0x2591e00, 0xc0014fc0b0, 0x3048db8, 0xc000fa40c0, 0xc000fa40c0)
        /home/runner/work/benthos/benthos/lib/input/http_client.go:308 +0x91
github.com/Jeffail/benthos/v3/lib/input.(*HTTPClient).ReadWithContext(0xc000e958c0, 0x306cce0, 0xc000fa40c0, 0xc000fa40c0, 0xc0014fc0b0, 0x10, 0x2591e00, 0xc000e18ce0)
        /home/runner/work/benthos/benthos/lib/input/http_client.go:260 +0xab
github.com/Jeffail/benthos/v3/lib/input/reader.(*AsyncPreserver).ReadWithContext(0xc00053f3c0, 0x306cce0, 0xc000fa40c0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/runner/work/benthos/benthos/lib/input/reader/async_preserver.go:171 +0x13b
github.com/Jeffail/benthos/v3/lib/input.(*AsyncReader).loop(0xc000269110)
        /home/runner/work/benthos/benthos/lib/input/async_reader.go:130 +0x495
created by github.com/Jeffail/benthos/v3/lib/input.NewAsyncReader
        /home/runner/work/benthos/benthos/lib/input/async_reader.go:63 +0x212
```

The problem occurred after adding a separate resource file for processor_resources. If I remove that file, the rate_limit is found and can be used. 

Is this a Bug or am I using benthos an unintended way?

I attach a minimal use case which shows the error:
[example.tar.gz](https://github.com/Jeffail/benthos/files/7013063/example.tar.gz)

**Comment by Jeffail** [comment]
Hey @mmsjomu, your configuration looks fine so I would expect it to work, and you definitely shouldn't be seeing a panic :sweat_smile:. Thanks for raising this, especially for providing a reproducible example, made it easy to put a fix together: https://github.com/Jeffail/benthos/commit/aba217578c664a82e997f82137f744fc55b10410

I'll aim to get a release out this evening as I don't think there's a work around beyond just not using processor/input resources that access rate limits.

**Comment by mmsjomu** [comment]
Hi @Jeffail, thank you for your fast response. Looking forward to the fixed version :)

**Comment by Jeffail** [comment]
Released: https://github.com/Jeffail/benthos/releases/tag/v3.53.0
